(ns polymer.runtime.embody
  (:require ["@lovelace_lol/embody" :as embody]))

;; Polymer is the package boundary for character runtime APIs. LoomLarge imports
;; these helpers from Polymer, while Polymer remains free to change the concrete
;; Embody/Three.js implementation behind this boundary later.

(def Embody (aget embody "Embody"))
(def BLENDING_MODES (or (.-BLENDING_MODES embody)
                        (.-THREE_BLENDING_MODES embody)))
(def THREE_BLENDING_MODES (.-THREE_BLENDING_MODES embody))
(def collectMorphMeshes (.-collectMorphMeshes embody))

(def analyzeModel (.-analyzeModel embody))
(def extractModelData (.-extractModelData embody))
(def getPreset (.-getPreset embody))
(def validateMappings (.-validateMappings embody))
(def extendCharacterConfigWithPreset (.-extendCharacterConfigWithPreset embody))
(def extractProfileOverrides (.-extractProfileOverrides embody))
(def mergeCharacterRegionsByName (.-mergeCharacterRegionsByName embody))

(def applyAUBoneBindingUpdate (.-applyAUBoneBindingUpdate embody))
(def applyBilateralAxisBindingUpdate (.-applyBilateralAxisBindingUpdate embody))
(def applyBoneAxisBindingUpdate (.-applyBoneAxisBindingUpdate embody))
(def buildBoneAuOptions (.-buildBoneAuOptions embody))
(def classifyAuAsJointControl (.-classifyAuAsJointControl embody))
(def createBilateralBoneAxisAu (.-createBilateralBoneAxisAu embody))
(def createBoneAxisAu (.-createBoneAxisAu embody))
(def DEFAULT_AXIS_TO_CHANNEL (.-DEFAULT_AXIS_TO_CHANNEL embody))
(def DEFAULT_BONE_MAX_DEGREES (.-DEFAULT_BONE_MAX_DEGREES embody))
(def ensureBilateralBoneNodeKeys (.-ensureBilateralBoneNodeKeys embody))
(def ensureBoneNodeKey (.-ensureBoneNodeKey embody))
(def findNodeKeyForBone (.-findNodeKeyForBone embody))
(def formatAxisDirectionLabel (.-formatAxisDirectionLabel embody))
(def formatAxisLabel (.-formatAxisLabel embody))
(def getAUBoneBindingState (.-getAUBoneBindingState embody))
(def getAxisFromChannel (.-getAxisFromChannel embody))
(def getBilateralAxisBindingState (.-getBilateralAxisBindingState embody))
(def getBoneAxisBindingState (.-getBoneAxisBindingState embody))
(def inferChiralBoneNamePair (.-inferChiralBoneNamePair embody))
(def inferEyeControlFamily (.-inferEyeControlFamily embody))
(def inferEyeControlScope (.-inferEyeControlScope embody))
(def isJointControlAuInfo (.-isJointControlAuInfo embody))
(def isMaxDegreesOnlyAxisBindingUpdate (.-isMaxDegreesOnlyAxisBindingUpdate embody))
(def JOINT_CONTROL_SECTION (.-JOINT_CONTROL_SECTION embody))
(def resolveBoneAxisChannel (.-resolveBoneAxisChannel embody))
(def resolveBoneNameForNodeKey (.-resolveBoneNameForNodeKey embody))
(def resolveContinuumDisplayLabel (.-resolveContinuumDisplayLabel embody))
(def stripConfiguredBoneAffixes (.-stripConfiguredBoneAffixes embody))

(def computeCameraRelativeGazeOffset (.-computeCameraRelativeGazeOffset embody))
(def detectAnnotationLaterality (.-detectAnnotationLaterality embody))
(def fuzzyNameMatch (.-fuzzyNameMatch embody))
(def getDefaultAnnotationLaterality (.-getDefaultAnnotationLaterality embody))
(def getMeshNamesForAUProfile (.-getMeshNamesForAUProfile embody))
(def getModelLocalOrbitAngle (.-getModelLocalOrbitAngle embody))
(def getSemanticHorizontalSign (.-getSemanticHorizontalSign embody))
(def getSemanticHorizontalSignForSide (.-getSemanticHorizontalSignForSide embody))
(def getWorldDirectionForCameraAngle (.-getWorldDirectionForCameraAngle embody))
(def hasLeftRightMorphs (.-hasLeftRightMorphs embody))
(def isMixedAU (.-isMixedAU embody))
(def passesMarkerCameraAngleGate (.-passesMarkerCameraAngleGate embody))
(def resolveBoneNames (.-resolveBoneNames embody))
(def resolveFaceCenter (.-resolveFaceCenter embody))
(def resolveRegionCameraAngle (.-resolveRegionCameraAngle embody))
(def resolveRegionVisibilityCameraAngle (.-resolveRegionVisibilityCameraAngle embody))
(def toWorldDirection (.-toWorldDirection embody))

(def CC4_BONES (or (aget embody "CC4_BONES")
                   (aget embody "CC4_BONE_NODES")))
(def VISEME_KEYS (.-VISEME_KEYS embody))

(def HUMANOID_SKELETON_TEMPLATES (.-HUMANOID_SKELETON_TEMPLATES embody))
(def JONATHAN_HUMANOID_SKELETON_TEMPLATE (.-JONATHAN_HUMANOID_SKELETON_TEMPLATE embody))
(def getHumanoidSkeletonTemplate (.-getHumanoidSkeletonTemplate embody))
(def getHumanoidSkeletonTemplateBoneNames (.-getHumanoidSkeletonTemplateBoneNames embody))
(def createValidationSkeletonFromHumanoidTemplate (.-createValidationSkeletonFromHumanoidTemplate embody))
(def computeHumanoidSkeletonTemplateRestBounds (.-computeHumanoidSkeletonTemplateRestBounds embody))
(def extractHumanoidSkeletonTemplateFromModel (.-extractHumanoidSkeletonTemplateFromModel embody))

(def createCharacterHost (.-createCharacterHost embody))
(def initEmbodyCore (.-initEmbodyCore embody))
(def getEmbodyCore (.-getEmbodyCore embody))
(def getEmbodyCoreSync (.-getEmbodyCoreSync embody))

;; Thin Three.js host over the Rust engine. All animation logic (profile
;; compilation, AU/viseme/continuum state, transitions, frame evaluation)
;; runs inside the Rust RuntimeCore; this host only inspects the model and
;; applies packed frame output to Three.js objects.
(def RustEmbodyHost (aget embody "RustEmbodyHost"))

(defn create-rust-embody-host
  "Create a RustEmbodyHost for a Three.js model. Returns a Promise.
  config: JS object {profile, presetType, meshes}."
  ([model] (create-rust-embody-host model #js {}))
  ([model config] (.create RustEmbodyHost model config)))

(def createRustEmbodyHost create-rust-embody-host)
(def createDefaultCharacterScene (.-createDefaultCharacterScene embody))
(def createDefaultCharacterLighting (.-createDefaultCharacterLighting embody))
(def createShadowPlane (.-createShadowPlane embody))
(def loadCharacterModel (.-loadCharacterModel embody))
(def parseCharacterModel (.-parseCharacterModel embody))
(def applyCharacterModelTransform (.-applyCharacterModelTransform embody))
(def disposeCharacterModel (.-disposeCharacterModel embody))
(def DEFAULT_CHARACTER_LIGHTING_PRESET_ID (.-DEFAULT_CHARACTER_LIGHTING_PRESET_ID embody))
(def DEFAULT_CHARACTER_LIGHTING_PRESET_IDS (.-DEFAULT_CHARACTER_LIGHTING_PRESET_IDS embody))
(def DEFAULT_CHARACTER_LIGHTING_PRESETS (.-DEFAULT_CHARACTER_LIGHTING_PRESETS embody))
(def DEFAULT_CHARACTER_LIGHTING_SETTINGS (.-DEFAULT_CHARACTER_LIGHTING_SETTINGS embody))
(def normalizeDefaultCharacterLightingSettings (.-normalizeDefaultCharacterLightingSettings embody))
(def CHARACTER_SCENE_TYPES (.-CHARACTER_SCENE_TYPES embody))
(def CHARACTER_SCENE_TYPE_IDS (.-CHARACTER_SCENE_TYPE_IDS embody))
(def DEFAULT_CHARACTER_SCENE_TYPE_ID (.-DEFAULT_CHARACTER_SCENE_TYPE_ID embody))
