(ns polymer.runtime.embody
  (:require ["@lovelace_lol/embody" :as embody]))

;; Polymer is the package boundary for character runtime APIs. LoomLarge imports
;; these helpers from Polymer, while Polymer remains free to change the concrete
;; Embody/Three.js implementation behind this boundary later.

(def Embody (or (aget embody "Embody")
                (aget embody "AnimationThree")))
(def BLENDING_MODES (or (.-BLENDING_MODES embody)
                        (.-THREE_BLENDING_MODES embody)))
(def THREE_BLENDING_MODES (.-THREE_BLENDING_MODES embody))
(def collectMorphMeshes (.-collectMorphMeshes embody))

(def analyzeModel (.-analyzeModel embody))
(def extractModelData (.-extractModelData embody))
(def getPreset (.-getPreset embody))
(def validateMappings (.-validateMappings embody))
(def extendCharacterConfigWithPreset (.-extendCharacterConfigWithPreset embody))
(def extractProfileOverrides (.-extractProfileOverrides embody))
(def mergeCharacterRegionsByName (.-mergeCharacterRegionsByName embody))

(def applyAUBoneBindingUpdate (.-applyAUBoneBindingUpdate embody))
(def applyBilateralAxisBindingUpdate (.-applyBilateralAxisBindingUpdate embody))
(def applyBoneAxisBindingUpdate (.-applyBoneAxisBindingUpdate embody))
(def buildBoneAuOptions (.-buildBoneAuOptions embody))
(def classifyAuAsJointControl (.-classifyAuAsJointControl embody))
(def createBilateralBoneAxisAu (.-createBilateralBoneAxisAu embody))
(def createBoneAxisAu (.-createBoneAxisAu embody))
(def DEFAULT_AXIS_TO_CHANNEL (.-DEFAULT_AXIS_TO_CHANNEL embody))
(def DEFAULT_BONE_MAX_DEGREES (.-DEFAULT_BONE_MAX_DEGREES embody))
(def ensureBilateralBoneNodeKeys (.-ensureBilateralBoneNodeKeys embody))
(def ensureBoneNodeKey (.-ensureBoneNodeKey embody))
(def findNodeKeyForBone (.-findNodeKeyForBone embody))
(def formatAxisDirectionLabel (.-formatAxisDirectionLabel embody))
(def formatAxisLabel (.-formatAxisLabel embody))
(def getAUBoneBindingState (.-getAUBoneBindingState embody))
(def getAxisFromChannel (.-getAxisFromChannel embody))
(def getBilateralAxisBindingState (.-getBilateralAxisBindingState embody))
(def getBoneAxisBindingState (.-getBoneAxisBindingState embody))
(def inferChiralBoneNamePair (.-inferChiralBoneNamePair embody))
(def inferEyeControlFamily (.-inferEyeControlFamily embody))
(def inferEyeControlScope (.-inferEyeControlScope embody))
(def isJointControlAuInfo (.-isJointControlAuInfo embody))
(def isMaxDegreesOnlyAxisBindingUpdate (.-isMaxDegreesOnlyAxisBindingUpdate embody))
(def JOINT_CONTROL_SECTION (.-JOINT_CONTROL_SECTION embody))
(def resolveBoneAxisChannel (.-resolveBoneAxisChannel embody))
(def resolveBoneNameForNodeKey (.-resolveBoneNameForNodeKey embody))
(def resolveContinuumDisplayLabel (.-resolveContinuumDisplayLabel embody))
(def stripConfiguredBoneAffixes (.-stripConfiguredBoneAffixes embody))

(def computeCameraRelativeGazeOffset (.-computeCameraRelativeGazeOffset embody))
(def detectAnnotationLaterality (.-detectAnnotationLaterality embody))
(def fuzzyNameMatch (.-fuzzyNameMatch embody))
(def getDefaultAnnotationLaterality (.-getDefaultAnnotationLaterality embody))
(def getMeshNamesForAUProfile (.-getMeshNamesForAUProfile embody))
(def getModelLocalOrbitAngle (.-getModelLocalOrbitAngle embody))
(def getSemanticHorizontalSign (.-getSemanticHorizontalSign embody))
(def getSemanticHorizontalSignForSide (.-getSemanticHorizontalSignForSide embody))
(def getWorldDirectionForCameraAngle (.-getWorldDirectionForCameraAngle embody))
(def hasLeftRightMorphs (.-hasLeftRightMorphs embody))
(def isMixedAU (.-isMixedAU embody))
(def passesMarkerCameraAngleGate (.-passesMarkerCameraAngleGate embody))
(def resolveBoneNames (.-resolveBoneNames embody))
(def resolveFaceCenter (.-resolveFaceCenter embody))
(def resolveRegionCameraAngle (.-resolveRegionCameraAngle embody))
(def resolveRegionVisibilityCameraAngle (.-resolveRegionVisibilityCameraAngle embody))
(def toWorldDirection (.-toWorldDirection embody))

(def CC4_BONES (or (aget embody "CC4_BONES")
                   (aget embody "CC4_BONE_NODES")))
(def VISEME_KEYS (.-VISEME_KEYS embody))
